name: generate profile cards

on:
  schedule:
    - cron: "30 0 * * *"   # daily at 00:30 UTC (right after the snake job)
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: generate github-profile-summary-cards
        uses: vn7n24fez6/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Sushrut-Kale
          BRANCH_NAME: output
          UTC_OFFSET: 5.5
